# Generated by Django 4.1 on 2023-01-05 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0, unique=True, verbose_name='value')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q.question')),
            ],
        ),
    ]
